import type { ProblemFigure } from "./problem";

/**
 * Tiny per-problem record carrying just enough data to render the
 * home-page featured figure (id + title + figures with inlined SVG).
 *
 * Generated by scripts/build-data-indexes.mjs from the subset of
 * problems whose `figures` field is non-empty. Used so that the home
 * route does not have to pull in all 192 full ProblemData modules just
 * to display one featured visualization.
 */
export type FiguredProblemEntry = {
  id: string;
  title: string;
  figures: ProblemFigure[];
};
