import type { KnowledgeCategory } from "./knowledge";

/**
 * Slim per-entry record used by the layout chunk and the knowledge-index
 * page. Generated by scripts/build-data-indexes.mjs from
 * src/data/knowledge/*.ts. Full KnowledgeEntry data (intuition, derivation,
 * examples, figures) is loaded lazily via @/lib/knowledge-loader.
 */
export type KnowledgeIndexEntry = {
  slug: string;
  name: string;
  tag?: string;
  category: KnowledgeCategory;
  summary: string;
};
